//
//  GameScene.swift
//  ProceduralGeometry
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine
import ProceduralGeometryExtension

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    /// Maps each tube's two (otherwise invisible) endpoint proxy entities to the tube they
    /// belong to and whether each is the start or end. Exactly two entries per tube, for its
    /// whole lifetime — populated once in `createDemoTube()` via `createTubeEndpointHandles`.
    /// Unlike the old per-control-point handle scheme, nothing here ever needs reindexing:
    /// inserted bends are pure data in `TubePathComponent.controlPoints`, with no entity of
    /// their own.
    var tubeEndpointHandles: [EntityID: (tubeId: EntityID, isStart: Bool)] = [:]

    /// The reverse of `tubeEndpointHandles`: each tube's own two proxy entities, for toggling
    /// their visibility when a tube becomes (in)active.
    var tubeEndpoints: [EntityID: (startHandleId: EntityID, endHandleId: EntityID)] = [:]

    /// Which tube, if any, is currently armed for editing — set by tapping the tube's own mesh
    /// (or one of its endpoint proxies), cleared by tapping anything else. Only an active tube's
    /// endpoints can be dragged; see `beginTubeDrag`.
    var activeTubeId: EntityID?

    /// The endpoint drag currently in progress, if any, paired with the proxy entity driving it
    /// — `TubeEndpointDrag` (from `ProceduralGeometryExtension`) has no idea proxy entities
    /// exist, so this demo tracks that pairing itself. See `GameScene+TubeEditing.swift`.
    ///
    /// Captured once when a gesture starts (the first frame `pickedEntityId` identifies one of
    /// the active tube's endpoint proxies) and held until that gesture ends — `pickedEntityId`
    /// isn't guaranteed to keep pointing at the same entity, or to stay non-nil, all the way
    /// through to the gesture's final `.ended`/`.cancelled` frame, and
    /// `SpatialManipulationSystem`'s own session only gets cleanly closed out if its lifecycle
    /// function is called on that final frame too — skipping it leaves the session stuck
    /// mid-drag, still targeting whatever it was last acting on.
    private var activeDrag: (drag: TubeEndpointDrag, proxyId: EntityID)?

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load your scene here
        ProceduralGeometryExtension.shared.install()

        let light = createEntity()
        setEntityName(entityId: light, name: "Directional Light")
        createDirLight(entityId: light)

        createDemoTube()

        setSceneReady(true)
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
    }

    /// Creates one procedural tube roughly at chest height, a short reach in front of where the
    /// immersive space starts, plus its two (invisible until tapped active) endpoint proxies.
    /// Tap the tube to arm it, then drag either endpoint — see `GameScene+TubeEditing.swift`.
    ///
    /// Two interior corners (at points 1 and 2) with `bendRadius` set, so both should render as
    /// smooth rounded bends rather than sharp miter joints — the thing to actually look at when
    /// manually verifying this in XR.
    private func createDemoTube() {
        let controlPoints: [SIMD3<Float>] = [
            SIMD3(-0.2, 1.2, -0.6),
            SIMD3(0.2, 1.2, -0.6),
            SIMD3(0.2, 1.4, -0.6),
            SIMD3(0.2, 1.4, -0.3),
        ]

        guard let tubeId = ProceduralGeometryExtension.shared.createTubeEntity(
            controlPoints: controlPoints,
            radius: 0.03,
            radialSegments: 16,
            capStart: true,
            capEnd: true,
            bendRadius: 0.08,
            name: "DemoTube"
        ) else {
            Logger.log(message: "❌ Failed to create demo tube")
            return
        }

        createTubeEndpointHandles(
            tubeId: tubeId,
            startPosition: controlPoints[0],
            endPosition: controlPoints[controlPoints.count - 1]
        )
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false {return}

        let state = InputSystem.shared.xrSpatialInputState

        // A tap (not a drag) on a tube, or on one of its endpoint proxies, arms it for editing;
        // a tap on anything else disarms whichever tube was previously active. This is checked
        // independently of the drag state below — a tap is a distinct, already-resolved gesture
        // (see SpatialInputTutorial.md), never concurrent with an active drag.
        if state.spatialTapActive {
            handleTubeTap(pickedEntityId: state.pickedEntityId)
        }

        // Latch onto an endpoint proxy only at the start of a gesture — once a drag is under
        // way, keep driving the same proxy regardless of what pickedEntityId reports frame to
        // frame. `beginTubeDrag` itself refuses to start unless the proxy's tube is the active
        // one, so a stray drag over an unarmed tube's (invisible) endpoint falls through to the
        // scene-manipulation branch below instead of doing anything tube-specific.
        //
        // Deliberately NOT gated on state.spatialTapActive: that flag means "this gesture
        // turned out to be a tap, not a drag" and is false for the entire duration of an
        // actual drag (see SpatialInputTutorial.md) — gating on it here meant a real drag
        // could never latch onto a proxy at all, so every attempt fell through to the
        // scene-root-drag branch below instead.
        if activeDrag == nil, let entityId = state.pickedEntityId, let drag = beginTubeDrag(proxyId: entityId) {
            activeDrag = (drag: drag, proxyId: entityId)
        }

        // Mutually exclusive: dragging an endpoint proxy must not also drag the scene root
        // under the same gesture, or everything in view appears to move together (the proxy
        // moves by its own delta *and* the whole scene shifts by that same delta).
        if var current = activeDrag {
            // Call every frame for as long as our gesture is live — including its last frame —
            // so SpatialManipulationSystem's own begin/update/end lifecycle actually reaches
            // `end` instead of getting stuck mid-drag on this entity.
            SpatialManipulationSystem.shared.processPinchTransformLifecycle(from: state)
            // ...then feed the proxy's current position into TubeEndpointDrag (the
            // axis-locked/90-degree-only constraint logic itself lives in
            // ProceduralGeometryExtension now) and move the proxy to wherever that reports back.
            // On the gesture's final frame this calls TubeEndpointDrag.end instead of .update —
            // pinch release is commonly accompanied by a small involuntary hand movement, which
            // .update's turn detection would otherwise be free to read as a deliberate redirect
            // and insert an unwanted bend right at the moment of release.
            let isGestureEnding = state.currentPhase == .ended || state.currentPhase == .cancelled
            updateEndpointDrag(&current.drag, proxyId: current.proxyId, isGestureEnding: isGestureEnding)
            activeDrag = current

            if isGestureEnding {
                activeDrag = nil
            }
        } else {
            // Nothing (or nothing of ours) picked — Pinch + Drag moves the scene root,
            // two-hands rotate rotates it.
            SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
                from: state,
                dragSensitivity: 10.0,
                rotateSensitivity: 1.0
            )
        }

        // Add your custom input handling here
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
